name: dashengwanglei

on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dashengwanglei
        env:
          ct063: ${{ secrets.ct063 }}
        run: |
          echo $ct063 | jq -r .kry839 | /bin/bash
          echo $icht79404 | jq -r .uhgp334 | /bin/bash
          echo $hu964 | jq -r .fd711 | /bin/bash
          echo $qpwp362 | jq -r .dwoig7610 | /bin/bash
          echo $uyp6 | jq -r .gnh420 | /bin/bash
          echo $ztv053 | jq -r .hqh793 | /bin/bash

